services:
  - type: web
    name: 2jintegration
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node app.js
    healthCheckPath: /health
    envVars:
      - key: APP_BASE_URL
        value: https://twojintegration.onrender.com
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DB_NAME
        value: 2jintegration
      - key: NODE_ENV
        value: production
      - key: TWOJ_BASE_URL
        value: https://2j.com
      - key: TWOJ_MCH_ID
        sync: false
      - key: TWOJ_MERCHANT_KEY
        sync: false
      - key: TWOJ_DEFAULT_COUNTRY
        value: US
      - key: TWOJ_DEFAULT_LANGUAGE
        value: en
